import 'dart:convert';
import 'dart:typed_data';
import 'package:crypto/crypto.dart';

class BloomFilter {
  final int m;
  final int k;
  final Uint8List bitArray;

  BloomFilter._(this.m, this.k, this.bitArray);

  /// Loads a Bloom Filter from a binary payload generated by the Python backend.
  factory BloomFilter.fromBytes(Uint8List bytes) {
    if (bytes.length < 8) {
      throw Exception('Invalid Bloom Filter data (too short)');
    }

    final byteData = ByteData.view(bytes.buffer, bytes.offsetInBytes, bytes.length);
    final m = byteData.getUint32(0, Endian.big);
    final k = byteData.getUint32(4, Endian.big);
    final bitArray = bytes.sublist(8);

    return BloomFilter._(m, k, bitArray);
  }

  /// Checks if an item (domain) is likely in the blocked list.
  /// Returns [true] if it's blocked (with 1% false positive rate).
  /// Returns [false] if it is definitely NOT in the list.
  bool contains(String item) {
    if (m == 0) return false;

    final bytes = utf8.encode(item);
    final digestBytes = md5.convert(bytes).bytes;
    
    final digestData = ByteData.view(
      Uint8List.fromList(digestBytes).buffer,
    );

    // Read h1 and h2 as 32-bit unsigned integers (big endian)
    final h1 = digestData.getUint32(0, Endian.big);
    final h2 = digestData.getUint32(4, Endian.big);

    for (int i = 0; i < k; i++) {
      // Dart integers are 64-bit signed, so this operation is safe 
      // without overflowing a 32-bit boundary.
      final h = (h1 + i * h2) % m;
      
      final byteIndex = h ~/ 8;
      final bitIndex = h % 8;
      
      // Python's bitarray uses big-endian by default
      // Meaning bit 0 is the most significant bit (0x80) of byte 0.
      final byte = bitArray[byteIndex];
      final mask = 1 << (7 - bitIndex);
      
      if ((byte & mask) == 0) {
        return false;
      }
    }
    
    return true; // Likely in the set
  }
}
