"""security_features

Revision ID: 51f4b2b268f6
Revises: a49421253249
Create Date: 2026-06-11 12:24:43.687557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51f4b2b268f6'
down_revision: Union[str, Sequence[str], None] = 'a49421253249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('safe_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('radius_meters', sa.Float(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('safe_zones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_safe_zones_id'), ['id'], unique=False)

    with op.batch_alter_table('time_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowed_apps', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_rules', schema=None) as batch_op:
        batch_op.drop_column('allowed_apps')

    with op.batch_alter_table('safe_zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_safe_zones_id'))

    op.drop_table('safe_zones')
    # ### end Alembic commands ###
