"""add pairing code

Revision ID: 61ed3188a776
Revises: 51f4b2b268f6
Create Date: 2026-06-19 22:32:37.846420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61ed3188a776'
down_revision: Union[str, Sequence[str], None] = '51f4b2b268f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pairing_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('pairing_code_expires_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('pairing_code_expires_at')
        batch_op.drop_column('pairing_code')

    # ### end Alembic commands ###
